name: PR Title Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - 'sprint*'

permissions:
  pull-requests: read

jobs:
  semantic-pr-title:
    name: Validate conventional PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            chore
            refactor
            test
            build
            ci
            perf
            revert
            style
